language: python
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
  - python setup.py test  # run test again for coverage
after_success:
  - coveralls
env:
  - TOXENV=py27-1.6
  - TOXENV=py27-1.7
  - TOXENV=py34-1.7
  - TOXENV=py27-1.8
  - TOXENV=py34-1.8
