language: python

sudo: false

python:
  - "3.5"

install:
  - pip install coverage coveralls codecov tox

script:
  - tox

after_success:
  - coveralls
  - codecov

env:
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19

  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19

  - TOXENV=py35-django18
  - TOXENV=py35-django19
